name: Run app.py every 5 minutes

on:
  schedule:
    - cron: '*/2 * * * *'  # Every 5 minutes
  workflow_dispatch:        # Optional: run manually from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run app.py
        run: python app.py
