name: Run app.py on schedule

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repo content

    - name: Install Microsoft SQL ODBC Driver 18
      run: |
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev  # Install SQL ODBC driver

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Run app.py
      run: |
        python app.py  # Execute the app.py script
